### ISSUE TITLE
[performance] Setup Redis for caching

### ISSUE THREAD

**Issue by DanH91** [purplship/purplship-dashboard#124]
**Is your feature request related to a problem? Please describe.**

Purplship server being built on Django can benefit from the ecosystem best practices to cater to users with high
scalability requirements.

**Describe the solution you'd like**

It is all about configuration. Setup the purplship Django settings to allow for turning on of caching with Redis.

**Comment by firxworx** [comment]
Please expose redis config via env as well. Please note some deploy scenarios might involve cloud-service equivalents to Redis e.g. AWS ElastiCache or want to run redis on their own instances / container services

**Comment by DanH91** [comment]
The foundations are there. Needs to be revisited with a specific use case
