### ISSUE TITLE
Interface Doesn't Support Multiple Parcels

### ISSUE THREAD

**Issue by minchaminder** [purplship/purplship-dashboard#140]
**Is your feature request related to a problem? Please describe.**
Interface Doesn't Support Multiple Parcels

**Comment by DanH91** [comment]
Hey @minchaminder ,
Thanks for reporting this. It is definitely a feature on the roadmap.

It is something that we are approaching carefully as it can bring complexity at the API level and might require good validation in the UI to safeguard/streamline the multi-parcel requests.

So far I've seen two ways to approach it either using batch processing or per carrier integration.

Although it might look straightforward with carriers like FedEx and Purolator, many others do not support multi-parcel shipping builtin so we need to define an abstraction that caters to all of them.
